# Protein domains configuration.

[Framework]
Name = "UniProt Protein Domains"
Name_verbose = "Retrieve UniProt protein domains given Ensembl transcript ID."
Version = "0.1"
Author = "YZ"

[Transcript]
text_file = "./src/data/transcript_list_DE.txt"  # Set the text file name containing Ensembl transcript ID per line
#csv_file = ".src/data/?.csv"  # Loading from a CSV file (comma separated). CURRENTLY NOT SUPPORTED
#csv_file_transcript_col_name = "Transcript_ID"  # column name in csv_file containing the transcript IDs. CURRENTLY NOT SUPPORTED


[Assembly]
version = "GRCh38"  # Set the Assembly to use (valid values are "GRCh38" or "GRCh37")

[IDs]
show_gene_id = true  # Set true [false] to enable [disable] reporting gene ID
show_gene_name = true  # Set true [false] to enable [disable] reporting gene name
show_protein_id = true  # Set true [false] to enable [disable] reporting protein ID
show_uniprot_id = true  # Set true [false] to enable [disable] reporting UniProt ID
show_uniprot_url = true  # Set true [false] to enable [disable] reporting UniProt URL

[Domains]
uniprot_features = ["Topological domain", "Transmembrane", "Domain", "Repeat", "Region"]  # Set the list of features to retrieve. Set to [] to retrieve all features.

[Output]
file = "./src/output/transcript_domains_DE.xlsx"  # Set the output excel file name
format = "expanded"  # Set to "basic": all transcripts and domains are listed in one excel sheet, where each row represents a domain.
                # Set to "compact": all transcripts and domains are listed in one excel sheet, where each row represents a transcript 
                # (all domains are aggregated in one cell, domains are '|' separated, domain's fields are ',' separated.)
                # Set to "expanded":  each transcript (and its domains) are listed in a separate excel sheet

[Debug]
enable = true  # Set to false [true] to disable [enable] debug prints
